version: '3.1'

services:
  rdb:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33006:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cxcxc

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mongo:
    image: mongo:4.2
    container_name: mongo_1
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  mario-server:
    container_name: cxcxc-mario
    image: pengbai/docker-supermario
    ports:
      - 8600:8080

  web-flask:
    build: .
    image: eb102:0.0.2
    ports:
      - 29999:5000
